#!/bin/sh
# bench.sh - ticket 161 AC#1 (r1 slice): does each D22 ban actually RING today?
#
# WHAT THIS IS. A fixture bench for the static gate `tools/d22scan`. For every
# numbered ban in tools/d22scan/main.go's `// Bans` roster it builds
#   (a) a known-violation sample root, and
#   (b) a known-clean sample root of the same shape,
# runs the scanner over that root with `-root`, and records whether the ban
# rang. The clean twin is not a courtesy: a sample that rings proves nothing
# unless the same-shaped clean sample stays silent (this repo has rejected two
# always-true criteria already).
#
# HOW IT WORKS AND WHY NOTHING LANDS IN THE TREE. The scanner takes exactly one
# knob, `-root <dir>` (tools/d22scan/main.go: main() -> checkRoot -> Scan). So a
# sample is a *fake repository root* laid out the way checkRoot demands:
# go.mod + tools/d22scan/allowlist.txt + internal/ + cmd/, with >= 10 production
# .go files, and every declared live scope non-empty (else the run exits 2 on
# "an empty instrument is not a verdict" instead of answering the question).
# Those roots live under
#   .scratch/wisp/probes/161/r1/runs/<cell>/...
# which is GENERATED by this script, never committed, and never inside internal/,
# cmd/, frontend/ or design/ of the real tree. The production bytes are not
# touched by anything here: this script reads tools/d22scan/** and writes only
# under its own directory.
#
# The generated roots are byte-identical for a given commit of THIS file, so a
# reading is recomputable: `sh bench.sh all` reproduces logs/<cell>.scan.log.
#
# SUBCOMMANDS
#   sh bench.sh build <cell>            instantiate runs/<cell>/ only
#   sh bench.sh run <cell>              build + scan + write logs/<cell>.scan.log
#   sh bench.sh all                     every cell, then logs/summary.tsv
#   sh bench.sh tool                    build the scanner binary into bin/
#   sh bench.sh gorun <cell>            same cell through `go run .` (proves the
#                                       binary under bin/ is not a stale stand-in)
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)      # probes/161/r1
# r1 -> 161 -> probes -> wisp -> .scratch -> repo root: five levels up.
root=$(CDPATH= cd -- "$here/../../../../.." && pwd)    # repository root
[ -f "$root/go.mod" ] || { echo "bench.sh: derived root \"$root\" has no go.mod - refusing" >&2; exit 2; }
cells="$here/cells"
runs="$here/runs"
logs="$here/logs"
bin="$here/bin/d22scan-probe161.exe"

# The cell roster. Order is: the skeleton control first (it is the reading that
# says "this layout itself is silent", so every other silence is attributable),
# then the ban order of main.go's `// Bans` block, then the `unparseable`
# finding type last.
CELLS="
skeleton-clean
b1-closure-bad
b1-named-bad
b1-clean
b1-probe-testfile
b2-bad
b2-clean
b2-probe-alias
b3-bad
b3-clean
b3-probe-structlit
b4-sub-bad
b4-unix-bad
b4-clean
b5-bad
b5-clean
b6-bad
b6-clean
b6-probe-comment
b7-bad
b7-clean
b8-scope-bad
b8-comment-clean
b8-probe-bands
unp-bad
unp-hides-bans
al-overbroad
"

# What each cell is expected to do, as "<ban-tag>|<expect>", expect = ring |
# silent | unknown (a probe measures, it does not assert). Written out here so
# the summary table can be read without opening the payloads.
expect_of() {
    case $1 in
    skeleton-clean)    echo "-|silent" ;;
    b1-closure-bad)    echo "bare-goroutine|ring" ;;
    b1-named-bad)      echo "bare-goroutine|ring" ;;
    b1-clean)          echo "bare-goroutine|silent" ;;
    b1-probe-testfile) echo "bare-goroutine|unknown" ;;
    b2-bad)            echo "pathresolver-bypass|ring" ;;
    b2-clean)          echo "pathresolver-bypass|silent" ;;
    b2-probe-alias)    echo "pathresolver-bypass|unknown" ;;
    b3-bad)            echo "plaintext-key|ring" ;;
    b3-clean)          echo "plaintext-key|silent" ;;
    b3-probe-structlit) echo "plaintext-key|unknown" ;;
    b4-sub-bad)        echo "wallclock-timeout|ring" ;;
    b4-unix-bad)       echo "wallclock-timeout|ring" ;;
    b4-clean)          echo "wallclock-timeout|silent" ;;
    b5-bad)            echo "mirror-hash|ring" ;;
    b5-clean)          echo "mirror-hash|silent" ;;
    b6-bad)            echo "panel-approval|ring" ;;
    b6-clean)          echo "panel-approval|silent" ;;
    b6-probe-comment)  echo "panel-approval|unknown" ;;
    b7-bad)            echo "internal-artifact-tool|ring" ;;
    b7-clean)          echo "internal-artifact-tool|silent" ;;
    b8-scope-bad)      echo "emoji|ring" ;;
    b8-comment-clean)  echo "emoji|silent" ;;
    b8-probe-bands)    echo "emoji|unknown" ;;
    unp-bad)           echo "unparseable|ring" ;;
    unp-hides-bans)    echo "bare-goroutine|unknown" ;;
    al-overbroad)      echo "pathresolver-bypass|silent" ;;
    *)                 echo "?|unknown" ;;
    esac
}

# ---------------------------------------------------------------- skeleton ----
# One fake wisp root. Everything in it is inert: no ban may ring on it, and its
# shape is exactly what checkRoot()/declaredScopes() demand, so an rc of 2
# ("empty instrument") can never masquerade as an answer.
skeleton() {
    d=$1
    mkdir -p "$d/tools/d22scan" "$d/internal/a" "$d/internal/tools" \
             "$d/cmd/probe" "$d/frontend" "$d/design"
    printf 'module probe161.example/fixture\n\ngo 1.24\n' >"$d/go.mod"
    # Deliberately EMPTY allowlist (comments only): a clean reading here must
    # mean "nothing matched", never "something suppressed it".
    {
        echo '# probe-bench allowlist for ticket 161 r1 - intentionally empty.'
        echo '# A clean verdict below means no rule matched; nothing is suppressed here.'
    } >"$d/tools/d22scan/allowlist.txt"
    # 10 production .go files live here (9) + cmd (1) = 10, plus internal/tools.
    i=0
    while [ $i -lt 9 ]; do
        printf 'package a\n\n// Skeleton file %d of the ticket-161 r1 probe bench.\nfunc Keep%d() int { return %d }\n' "$i" "$i" "$i" >"$d/internal/a/skeleton$i.go"
        i=$((i + 1))
    done
    printf 'package tools\n\n// Skeleton carrier for ban #7 scope internal/tools/.\nfunc ToolName() string { return "artifacts.list" }\n' >"$d/internal/tools/probe_tool.go"
    printf 'package main\n\n// Skeleton carrier for cmd/ (bans #1-5 + ban #8 scope cmd/).\nfunc main() { _ = 1 }\n' >"$d/cmd/probe/main.go"
    printf 'export const skeleton = 1\n' >"$d/frontend/skeleton.ts"
    printf '<!doctype html>\n<title>probe skeleton</title>\n' >"$d/design/skeleton.html"
}

# ---------------------------------------------------------------- payloads ---
payload() {
    cell=$1
    d=$2
    case $cell in
    skeleton-clean)
        # control: nothing added on top of the skeleton
        :
        ;;

    # ---- ban #1 bare-goroutine (AST *ast.GoStmt, scope internal/+cmd/ non-test)
    b1-closure-bad)
        cat >"$d/internal/a/p_b1.go" <<'GOEOF'
package a

// Cell b1-closure-bad. The pre-R16 matcher saw ONLY this shape, so "clean" used
// to mean "no bare closures" rather than "nothing bypasses Spawn".
func spawnClosure() {
	go func() { _ = 1 }()
}
GOEOF
        ;;
    b1-named-bad)
        cat >"$d/internal/a/p_b1.go" <<'GOEOF'
package a

func probeReader() { _ = 1 }

// Cell b1-named-bad: R16#1's widening - a NAMED call spawns exactly as unsafely
// as the closure above, and it is the shape the gate used to be blind to.
func spawnNamed() { go probeReader() }
GOEOF
        ;;
    b1-clean)
        cat >"$d/internal/a/p_b1.go" <<'GOEOF'
package a

func probeReader() { _ = 1 }

// Cell b1-clean. Same file, same words, no `go` keyword: the sanctioned spawn
// point is observe.Registry.Spawn, spelled here as a plain call because this
// fake root carries no observe package. The banned shapes appear in this
// comment as PROSE only (go func() {}() and go probeReader()), which is exactly
// what an AST ban must not fire on and a text grep would.
func spawnSanctioned() { RegistrySpawn(probeReader) }

func RegistrySpawn(fn func()) { fn() }
GOEOF
        ;;
    b1-probe-testfile)
        # Scope probe, not a blind spot: bans #1-5 are production, non-test by
        # declaration (main.go's doc comment). Measured anyway, because nobody
        # has ever read the number.
        cat >"$d/internal/a/p_b1_test.go" <<'GOEOF'
package a

func TestSpawnShape(t *testing.T) {
	go func() { _ = 1 }()
}
GOEOF
        ;;

    # ---- ban #2 pathresolver-bypass (AST selector, receiver named `filepath`)
    b2-bad)
        cat >"$d/internal/a/p_b2.go" <<'GOEOF'
package a

import "path/filepath"

// Cell b2-bad: both arms of the ban, in production scope, and this fixture's
// allowlist is empty, so nothing here is a sanctioned exception.
func norm(p string) string { return filepath.Clean(p) }

func absOf(p string) (string, error) { return filepath.Abs(p) }
GOEOF
        ;;
    b2-clean)
        cat >"$d/internal/a/p_b2.go" <<'GOEOF'
package a

import "path/filepath"

// Cell b2-clean: the sibling filepath calls that are NOT the banned pair, plus
// a same-named method on a different receiver - the ban is about Clean/Abs on
// the stdlib package, not about the word "Clean".
func join(a, b string) string { return filepath.Join(a, b) }

func base(p string) string { return filepath.Base(p) }

func dir(p string) string { return filepath.Dir(p) }

func rel(a, b string) (string, error) { return filepath.Rel(a, b) }

type fakeResolver struct{}

func (fakeResolver) Clean() string { return "." }
GOEOF
        ;;
    b2-probe-alias)
        cat >"$d/internal/a/p_b2.go" <<'GOEOF'
package a

import fp "path/filepath"

// Cell b2-probe-alias: the SAME filesystem decision, reached through an aliased
// import. The ban's wording ("filepath.Clean / filepath.Abs outside the
// allowlist") does not license an alias; the matcher keys on the local
// identifier name. This cell exists to read out which of the two the gate
// implements.
func norm(p string) string { return fp.Clean(p) }
GOEOF
        ;;

    # ---- ban #3 plaintext-key (AST ValueSpec + AssignStmt, shape-guarded)
    b3-bad)
        cat >"$d/internal/a/p_b3.go" <<'GOEOF'
package a

// Cell b3-bad. BOTH values are SYNTHETIC strings invented for this fixture -
// they are not, and must never become, a real credential of any kind.
// Two arms of the same ban: a const declaration and an assignment.
const probeAPIKey = "PROBE161NOTACREDENTIALED123456"

func loadProbe() string {
	probeSecret := "PROBE161SECRETNOTAKEY000001"
	return probeSecret
}
GOEOF
        ;;
    b3-clean)
        cat >"$d/internal/a/p_b3.go" <<'GOEOF'
package a

import "os"

// Cell b3-clean: every identifier here PASSES the name gate (each ends in a
// secret word), so what has to save it is the value shape - the three ref
// prefixes and the entropy guards. If this cell rings, ban #3 fires on names
// alone and is not the rule it is documented to be.
const envAPIKey = "env:WISP_PROBE_API_KEY"

func loadProbe() (string, string) {
	placeSecret := "placeholder-PROBE161-123456"
	oauthToken := "pay-per-token"
	vaultRefSecret := "ref:PROBE161NOTAKEY1234567890"
	_ = os.Getenv
	return placeSecret + oauthToken, vaultRefSecret + envAPIKey
}
GOEOF
        ;;

    # ---- ban #4 wallclock-timeout (line regex over non-comment lines)
    b4-sub-bad)
        cat >"$d/internal/a/p_b4.go" <<'GOEOF'
package a

import "time"

// Cell b4-sub-bad: arm 1, `.Sub(time.Now())` on a deadline.
func drift(deadline time.Time) time.Duration { return deadline.Sub(time.Now()) }
GOEOF
        ;;
    b4-unix-bad)
        cat >"$d/internal/a/p_b4.go" <<'GOEOF'
package a

import "time"

// Cell b4-unix-bad: arm 2, a unix second on a line that also says "timeout".
func timeoutAt() int64 {
	timeoutUnix := time.Now().Unix() + 30
	return timeoutUnix
}
GOEOF
        ;;
    b4-clean)
        cat >"$d/internal/a/p_b4.go" <<'GOEOF'
package a

import "time"

// Cell b4-clean: monotonic-safe deltas and a plain Duration subtraction. The
// word "timeout" appears (it is the variable's job) but never beside a
// time.Now().Unix() call, and no Sub() takes time.Now() as its argument.
func remaining(deadline time.Time) time.Duration { return time.Until(deadline) }

func since(start time.Time) time.Duration { return time.Since(start) }

func between(a, b time.Time) time.Duration { return b.Sub(a) }

func timeoutValue(d time.Duration) int { return int(d.Seconds()) }
GOEOF
        ;;

    # ---- ban #5 mirror-hash (two regexes on the SAME non-comment line)
    b5-bad)
        cat >"$d/internal/a/p_b5.go" <<'GOEOF'
package a

// Cell b5-bad: hash material named on the same line as a mirror (C29/F3:
// hashes come from the signed manifest only).
func pick() string {
	mirrorSHA256 := hexOf(mirrorDigest)
	return mirrorSHA256
}
GOEOF
        ;;
    b5-clean)
        cat >"$d/internal/a/p_b5.go" <<'GOEOF'
package a

// Cell b5-clean: the two halves apart. A hash word with no mirror anywhere on
// the line, and a mirror URL with no hash word on its line.
func pickManifest() string { return hexOf(manifestDigest) }

func pickMirror() string { return baseURL + "/file.tar" }
GOEOF
        ;;

    # ---- ban #6 panel-approval (raw line regex over EVERY file in frontend/)
    b6-bad)
        cat >"$d/frontend/p_b6.ts" <<'GOEOF'
// Cell b6-bad: the panel deciding ALLOW is the banned shape (D33/F2).
export async function decide(id: string) {
  return bridge.invoke("approval.decide", { id, verdict: "allow" });
}
GOEOF
        ;;
    b6-clean)
        cat >"$d/frontend/p_b6.ts" <<'GOEOF'
// Cell b6-clean: the panel may ASK, which is the only thing it is allowed to do.
export async function ask(id: string) {
  return bridge.invoke("approval.request", { id });
}
GOEOF
        ;;
    b6-probe-comment)
        cat >"$d/frontend/p_b6.ts" <<'GOEOF'
// Cell b6-probe-comment: the literal method name in PROSE only, no call at all.
// Ban #8 got a comment exemption from Q-46(c); ban #6 runs through walkText,
// which has no comment stripping. This cell reads out whether that asymmetry
// is real today.
export const note = "the host owns approval.decide, never the panel";
GOEOF
        ;;

    # ---- ban #7 internal-artifact-tool (line regex, internal/tools/, .go only)
    b7-bad)
        cat >"$d/internal/tools/p_b7.go" <<'GOEOF'
package tools

// Cell b7-bad: both alternatives of the matcher - a dotted internal.* tool name
// and the bare "spill" name (D34 note 2).
const artifactWriteTool = "internal.artifacts.write"

const spillTool = "spill"

func Names7() (string, string) { return artifactWriteTool, spillTool }
GOEOF
        ;;
    b7-clean)
        cat >"$d/internal/tools/p_b7.go" <<'GOEOF'
package tools

// Cell b7-clean: the near misses, spelled with NO quoted literal anywhere in
// this comment (b7-clean.first-run-rang-on-comment.log records what happened
// when this prose did carry one - ban #7 has no comment exemption).
const artifactWriteTool = "artifacts.write"

const internalToolsPkg = "internaltools.write"

func Names7() (string, string) { return artifactWriteTool, internalToolsPkg }
GOEOF
        ;;
    b3-probe-structlit)
        cat >"$d/internal/a/p_b3s.go" <<'GOEOF'
package a

// Cell b3-probe-structlit: the same plaintext literal reached through a STRUCT
// FIELD instead of a declaration or an assignment. The ban's wording says
// "key/token/secret-named identifier assigned a string literal"; the matcher
// walks ValueSpec and AssignStmt with an Ident on the left. A composite
// literal has neither. This cell reads out which of the two the gate does.
type probeCfg struct{ APIKey string }

var probeLoaded = probeCfg{APIKey: "PROBE161NOTACREDENTIALED987654"}
GOEOF
        ;;

    # ---- ban #8 emoji: ONE cell, four live scopes, one glyph per scope
    b8-scope-bad)
        cat >"$d/internal/a/p_b8.go" <<'GOEOF'
package a

// Cell b8-scope-bad: a glyph in a STRING (non-comment) - the shape Q-46(c)
// kept strict on purpose.
const okLabelInternal = "✅ done"

func Keep8() int { return len(okLabelInternal) }
GOEOF
        cat >"$d/cmd/probe/p_b8.go" <<'GOEOF'
package main

const okLabelCmd = "✅ done"
GOEOF
        cat >"$d/design/p_b8.html" <<'GOEOF'
<!doctype html>
<title>probe</title>
<p>built ✅</p>
GOEOF
        cat >"$d/frontend/p_b8.ts" <<'GOEOF'
export const okLabel = "built ✅";
GOEOF
        ;;
    b8-comment-clean)
        cat >"$d/internal/a/p_b8.go" <<'GOEOF'
package a

// Cell b8-comment-clean: the same glyph in prose only, in every scope.
// Q-46(c) exempts comments and keeps strings strict, so this is the clean twin
// of b8-scope-bad - same shape, one axis changed. ✅
func Keep8() int { return 8 }
GOEOF
        cat >"$d/cmd/probe/p_b8.go" <<'GOEOF'
package main

// ✅ prose only, exempt per Q-46(c)
GOEOF
        cat >"$d/design/p_b8.html" <<'GOEOF'
<!doctype html>
<title>probe</title>
<!-- built ✅ - an HTML comment, a marker the coarse classifier does carry -->
GOEOF
        cat >"$d/frontend/p_b8.ts" <<'GOEOF'
// export const okLabel = "built ✅";  <- commented out, still a // marker
export const okLabel = "built";
GOEOF
        ;;
    b8-probe-bands)
        cat >"$d/internal/a/p_b8.go" <<'GOEOF'
package a

// Cell b8-probe-bands: four glyphs, all in strings (never comments), so no
// exemption applies and only the character class decides. Per main.go the bands
// are 1F000-1FAFF, 2200-22FF, 2600-27BF, 2B00-2BFF, FE0F, 1F1E6-1F1FF, with the
// arrow band 2190-21FF and the circled-number band 2460-24FF deliberately
// absent. AGENTS.md states the practical consequence: U+2192 is not caught and
// U+2713 / U+2264 are. This cell is that sentence measured.
const arrowBand = "→"      // U+2192, outside every scanned band
const circledBand = "①"    // U+2460, outside every scanned band
const checkGlyph = "✓"     // U+2713, inside 2600-27BF
const mathGlyph = "≤"      // U+2264, inside the Q-46(c) math band

func Keep8() int { return len(arrowBand + circledBand + checkGlyph + mathGlyph) }
GOEOF
        ;;

    # ---- `unparseable`: a FINDING TYPE, not a numbered ban
    unp-bad)
        # The file also carries a ban #8 string glyph on purpose: ban #8 is a
        # LINE walk, so it is the only ban that can still read a file the AST
        # bans (#1-3) and the line bans (#4-5) both give up on.
        cat >"$d/internal/a/p_unp.go" <<'GOEOF'
package a

const brokenLabel = "✅"

func broken( {
	return
GOEOF
        ;;
    al-overbroad)
        cat >"$d/internal/a/p_al.go" <<'GOEOF'
package a

import "path/filepath"

// Cell al-overbroad: two different banned shapes in one file, and a fixture
// allowlist line that suppresses ONE of them by a directory prefix. What this
// measures is the suppression door itself: reviewed text in
// tools/d22scan/allowlist.txt can blanket a whole subtree for one ban, and the
// run still prints the other bans' findings as usual.
func spawnClosure() {
	go func() { _ = 1 }()
}

func norm(p string) string { return filepath.Clean(p) }
GOEOF
        {
            echo '# fixture allowlist for cell al-overbroad - NOT the shipped one.'
            printf 'pathresolver-bypass\tinternal/\tprobe: deliberately over-broad directory prefix\n'
        } >"$d/tools/d22scan/allowlist.txt"
        ;;
    unp-hides-bans)
        cat >"$d/internal/a/p_unp.go" <<'GOEOF'
package a

import "path/filepath"

// Cell unp-hides-bans: the SAME file carrying two other banned shapes under a
// syntax error. scanGoFile() returns as soon as parser.ParseFile fails, so the
// question this cell asks is whether a file can buy immunity from bans #1-5 by
// not parsing - and what the run prints instead.
func spawnClosure() {
	go func() { _ = 1 }()
}

func norm(p string) string { return filepath.Clean(p) }

func broken( {
	return
GOEOF
        ;;

    *)
        echo "bench.sh: no such cell: $cell" >&2
        return 2
        ;;
    esac
}

# ---------------------------------------------------------------- driver -----
build() {
    cell=$1
    d="$runs/$cell"
    mkdir -p "$d"
    skeleton "$d"
    payload "$cell" "$d"
    echo "$cell" >"$d/.cell"
}

tool() {
    mkdir -p "$here/bin"
    ( cd "$root/tools/d22scan" && go build -o "$bin" . )
    echo "built: $bin from tools/d22scan at $root"
}

run() {
    cell=$1
    build "$cell"
    mkdir -p "$logs"
    out="$logs/$cell.scan.log"
    {
        echo "# cell: $cell"
        echo "# command: (cd \"$root/tools/d22scan\" && $bin -root \"$runs/$cell\")"
    } >"$out"
    # `|| rc=$?` instead of a set +e/-e pair: a function that re-enables errexit
    # is a function that kills its caller's loop one line later.
    rc=0
    ( cd "$root/tools/d22scan" && "$bin" -root "$runs/$cell" ) >>"$out" 2>&1 || rc=$?
    echo "# rc=$rc" >>"$out"
    return $rc
}

summary() {
    mkdir -p "$logs"
    t="$logs/summary.tsv"
    printf 'cell\texpected_ban\texpectation\trc\tring_count\trig_said_ban\tfinding_lines\n' >"$t"
    for cell in $CELLS; do
        out="$logs/$cell.scan.log"
        [ -f "$out" ] || { echo "bench.sh: missing log for $cell" >&2; continue; }
        rc=$(sed -n 's/^# rc=//p' "$out")
        spec=$(expect_of "$cell")
        ban=${spec%%|*}
        exp=${spec##*|}
        hits=$(grep -cE '^[A-Za-z0-9_./-]+:[0-9]+: \[' "$out" || true)
        said=no
        if [ "$ban" != "-" ] && grep -qE ": \[$ban\] " "$out"; then said=yes; fi
        lines=$(grep -E '^[A-Za-z0-9_./-]+:[0-9]+: \[' "$out" | tr '\n' '~' || true)
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$cell" "$ban" "$exp" "$rc" "$hits" "$said" "$lines" >>"$t"
    done
    column -t -s '	' "$t"
}

all() {
    tool
    for cell in $CELLS; do
        set +e
        run "$cell"
        rc=$?
        set -e
        echo "cell=$cell rc=$rc"
    done
    summary
}

gorun() {
    cell=$1
    build "$cell"
    ( cd "$root/tools/d22scan" && go run . -root "$runs/$cell" )
    echo "# go run rc=$?"
}

case ${1:-} in
build)   build "$2" ;;
run)     set +e; run "$2"; echo "rc=$?"; ;;
all)     all ;;
tool)    tool ;;
gorun)   set +e; gorun "$2"; ;;
cells)   for c in $CELLS; do echo $c; done ;;
*)       echo "usage: sh bench.sh {all|build <cell>|run <cell>|gorun <cell>|tool|cells}" >&2; exit 2 ;;
esac
